### ISSUE TITLE
[Feature]: Node taints on oscmachinetemplates

### ISSUE THREAD

**Issue by mickaelicoptere** [outscale/cluster-api-provider-outscale#268]
### Explain problem to solve

Hi, I'd like to be able to apply node taints on a `machinedeployment` or `oscmachinetemplate` declaratively.
 I didn't find this field in the specs of `oscmachinetemplates.infrastructure.cluster.x-k8s.io`, nor examples to show how to do that. 

I also tried to put the annotations `capacity.cluster-autoscaler.kubernetes.io/taints` on the MachineDeployment. (from cluster-autoscaler: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#pre-defined-labels-and-taints-on-nodes-scaled-from-zero).

But I still don't manage to get the taints on the node provisionned in our outscale cluster using the image `cluster-api-outscale-controllers:v0.2.3` of the cluster-api provider.

And using the version `1.27.2` of cluster-autoscaler

### Describe the solution you would like

I'd like to be able to specify node taints on a OscMachineTemplate resource. Like:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
...
spec:
  template:
    ...
    spec:
      taints:
        - key: key1
          value: '1'
          effect: NoSchedule
        - key: key1
          value: '1'
          effect: NoExecute
```

### Additional context

We have a management cluster and a workload cluster on outscale deployed using cluster-api using cluster-api-provider-outscale

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.28.2
- OS (e.g. from `/etc/os-release`): ubuntu-2204-2204
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version: v0.2.3
- cluster-api version: v1.5.1
- Install tools: calico
- Kubernetes Distribution: kubeadm
- Kubernetes Diestribution version: v1.25.10
```

**Comment by outscale-vbr** [comment]
Hi @mickaelicoptere ,
If you use kubeadm as a bootstrapper, you can use taint in kubeadmconfig:

```
kubeadmConfigSpec:
  initConfiguration:
     nodeRegistration:
       taints:
       - key: "key1"
         value: "value1"
         effect: "NoSchedule"
  joinConfiguration:
    nodeRegistration:
       taints: 
       - key: "key1"
          value: "value1"
          effect: "NoSchedule"
        
```
We will not implement in machinedeployment like aws (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/794/files) because we don't manage our own integration of kubeadm.

Best regards,
Vincent BAER**
