### ISSUE TITLE
[Feature]: Allow to reuse parts of existing infrastructure

### ISSUE THREAD

**Issue by pli01** [outscale/cluster-api-provider-outscale#381]
### Explain problem to solve

Need to reuse part of existing pre deployed infrastructure with cluster-api Outscale deployment:
- reuse infrastructure resources (VPC, LB, subnet, nat, igw, public IP, bastion ..)
- to  improve deployment time 
- to reduce cost

### Describe the solution you would like

Cluster-api provider outscale need to support the following:
reuse infrastructure parts, with ID or TAG
- preexisting VPC
- preexisting subnet (public or private)
- preexisting NAT or IGW
- preexisting LB
- preexisting bastion

### Additional context

We  need to deploy with multiple providers and predefined topology

for example, others cluster-api provider support it :
- cluster-api aws  https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure#bring-your-own-aws-infrastructure
- cluster-api openstack https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration#use-existing-router

### Environment

```markdown
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version:
- cluster-api version:
- Install tools:
- Kubernetes Distribution:
- Kubernetes Diestribution version:
```

**Comment by alistarle** [comment]
Hi ! I also definitely need this feature. I see in the CRD we can pass `resourceId` in many object (net/subnet/igw...), have you tested it ?

I'm planning to do it in the following days so I will keep you updated

**Comment by jfbus** [comment]
Currently planned for v0.5.0 for most resources, some resources might be implemented in v0.6.0

**Comment by jfbus** [comment]
The current plan is to add a global flag is OscCluster to activate network reuse.

In network reuse, CAPOSC expects the following to be present:
- a Net & its Subnets
- an Internet Service and necessary NAT services
- route tables
- a bastion
- security groups

Reusing loadbalancers is more complicated (but should be possible), and will be discussed later.

`net.resourceId` and the subnet IP ranges will need to be configured (no need to configure the subnet resource IDs, the IP range allows CAPOSC to find the subnet and the security groups ids).

To simplify references to subnets and security groups from vms, roles are defined:

OscCluster
```yaml
network:
  net:
    resourceId: vpc-xxx
    reuseExisting: true
  subnets:
  - ipRange: 10.0.1.0/24
    role: public
  - ipRange: 10.0.2.0/24
    role: controlplane
  - ipRange: 10.0.3.0/24
    role:worker
    subRegion: eu-west-2a 
  - ipRange: 10.0.4.0/24
    role:worker
    subRegion: eu-west-2b 
  securityGroups:
  - resourceId: sg-xxx
    role: controlplane
```

No changes are necessary on OscMachineTemplate, role and subregion allow us to find the right subnet and security groups.

Resource tracking needs to be refactored, some additional changes are planned:
* limiting rewriting of spec, to avoid retriggering reconciliation,
* simplifying reference maps in status to improve readability,
* replacing IaaS reference search, previously using the name tag, with a more reliable attribute, and allow more user frindly nameS.

**Comment by alistarle** [comment]
Hi,

Thanks for taking this feature in account !

With a global flag comparing to our implementation, you need to manage your security group (which can be cumbersome at some point), can't we use the "reuseExisting" at a lower level (per resources) to be more granular ?

**Comment by jfbus** [comment]
1. There are some complexities in mixing managed/non-managed resources. i.e. computing subnets ranges in an existing net (with other subnets) is complex.
=> I'm not a big fan of allowing CAPOSC managed subnets on an existing net

2. What is the point of not reusing routing tables/internet gateways/nat services when subnet is reused ?

That leaves us with SGs... You are right, managing rules is cumbersome.

We could add a separate flag for SGs (and only for SGs).

As SG is a list, we could move the existing flag to a new object.

```yaml
reuseExisting:
  net: true
  securityGroups: true
```
