### ISSUE TITLE
[Bug]: Cluster API operator created 3325 machines

### ISSUE THREAD

**Issue by pierreozoux** [outscale/cluster-api-provider-outscale#543]
### What happened

I deployed a new MachineDeployment with the older version of kubernetes.

(Control plane is in 1.30.12, and I tried to add a MD with version 1.29.15)

There was an error in the describe:
```
      Message:               Scaling up from 0 to 8 replicas is blocked because:
* MachineSet version (1.29.15) and ControlPlane version (1.30.12) do not conform to kubeadm version skew policy as kubeadm only supports joining with the same major+minor version as the control plane ("KubeadmVersionSkew" preflight check failed)
```

I updated the MD file for the worker with the right kubernetes version:

```
(⎈|simone-veil:hedy-lamarr)➜  cluster-api git:(main) ✗ k apply -f ./worker.yml
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/hedy-lamarr-md-0 unchanged
machinedeployment.cluster.x-k8s.io/hedy-lamarr-md-0-red configured
oscmachinetemplate.infrastructure.cluster.x-k8s.io/hedy-lamarr-md-0-red unchanged
```

I wanted to have 8 replicas, and I was surprised already to get 12 nodes:
```
(⎈|simone-veil:hedy-lamarr)➜  cluster-api git:(main) ✗ k get machinedeployments.cluster.x-k8s.io 
NAME                   CLUSTER       REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE     VERSION
hedy-lamarr-md-0       hedy-lamarr   9          9       9         0             Running     445d    v1.29.15
hedy-lamarr-md-0-red   hedy-lamarr                                12            ScalingUp   9m39s   v1.30.12
(⎈|simone-veil:hedy-lamarr)➜  cluster-api git:(main) ✗ k get machinesets.cluster.x-k8s.io 
NAME                         CLUSTER       REPLICAS   READY   AVAILABLE   AGE     VERSION
hedy-lamarr-md-0-b5cjz       hedy-lamarr   9          9       9           28d     v1.29.15
hedy-lamarr-md-0-j9db7       hedy-lamarr   0          0       0           90d     v1.28.14
hedy-lamarr-md-0-red-ggw62   hedy-lamarr                                  9m52s   v1.29.15
hedy-lamarr-md-0-red-xshmx   hedy-lamarr                                  21s     v1.30.12
```

I deleted the machine set:
```
(⎈|simone-veil:hedy-lamarr)➜  cluster-api git:(main) ✗ k delete machinesets.cluster.x-k8s.io hedy-lamarr-md-0-red-ggw62
machineset.cluster.x-k8s.io "hedy-lamarr-md-0-red-ggw62" deleted
(⎈|simone-veil:hedy-lamarr)➜  cluster-api git:(main) ✗ k get machinedeployments.cluster.x-k8s.io 
NAME                   CLUSTER       REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE    VERSION
hedy-lamarr-md-0       hedy-lamarr   9          9       9         0             Running     445d   v1.29.15
hedy-lamarr-md-0-red   hedy-lamarr                                8             ScalingUp   10m    v1.30.12
```

and the describe of the MD got crazy somehow:
```
(⎈|simone-veil:hedy-lamarr)➜  cluster-api git:(main) ✗ k describe machinesets.cluster.x-k8s.io hedy-lamarr-md-0-red-xshmx
...
Events:
  Type    Reason            Age                 From                   Message
  ----    ------            ----                ----                   -------
  Normal  SuccessfulCreate  81s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-dt2dh"
  Normal  SuccessfulCreate  81s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-gf9qf"
  Normal  SuccessfulCreate  81s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-gjpbg"
  Normal  SuccessfulCreate  80s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-tl5qp"
  Normal  SuccessfulCreate  80s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-8s2v2"
  Normal  SuccessfulCreate  80s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-zp9pt"
  Normal  SuccessfulCreate  79s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-bqctz"
  Normal  SuccessfulCreate  79s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-jbczf"
  Normal  SuccessfulCreate  79s                 machineset-controller  Created machine "hedy-lamarr-md-0-red-xshmx-767gs"
  Normal  SuccessfulCreate  78s (x16 over 79s)  machineset-controller  (combined from similar events): Created machine "hedy-lamarr-md-0-red-xshmx-tm5g7"
```
```
 k get machine | wc -l
3325
```

### Step to reproduce

not sure...

### Expected to happen

I excpected to get 8 new machines in 1.30.12, not 3325 :)

### Add anything

.

### cluster-api output

too many logs...

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): 1.30.12
- OS (e.g. from `/etc/os-release`):
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version: 0.4.0
- cluster-api version: 1.9.6
- Install tools:
- Kubernetes Distribution:
- Kubernetes Diestribution version:
```

**Comment by pierreozoux** [comment]
je viens de delete le md et de le recréer, meme chose :/

**Comment by pierreozoux** [comment]
Ok, I got the issue in the MD object, this was my object:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: hedy-lamarr
  name: hedy-lamarr-md-0
  namespace: hedy-lamarr
spec:
  clusterName: hedy-lamarr
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 9
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: hedy-lamarr
      cluster.x-k8s.io/deployment-name: hedy-lamarr-md-0
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: hedy-lamarr
        cluster.x-k8s.io/deployment-name: hedy-lamarr-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: hedy-lamarr-md-0
      clusterName: hedy-lamarr
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OscMachineTemplate
        name: hedy-lamarr-md-0-blue
      version: v1.29.15
```

and I changed the name of the object to: `name: hedy-lamarr-md-0-red`

I think it didn't match the `label / selector` part.
Correcting it fixed it.

But I still think it is a bug, in the sense that when you make an error in this part in a kube deploy, I don't recall kube trying to create 100s of pods :)
